kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pkg-distributor
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph
  resources:
    requests:
      storage: 10Gi
